# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-Ea38PGGvuHu4VB_NkEflJks30ep9ES
"""

n=int(input())
for i in range(1,n+1):
  print(i)

n=int(input())
i=1
while i<=n:
  print(i)
  i+=1

